export const lightTheme = {
  mode: 'light',
  background: '#F7F7FB',
  surface: '#FFFFFF',
  card: '#FFFFFF',
  text: '#1A1A2E',
  textSecondary: '#6B6B85',
  border: '#E7E7F0',
  primary: '#6C5CE7',
  primaryText: '#FFFFFF',
  accent: '#FF6B81',
  success: '#2ECC71',
  danger: '#E74C3C',
  inputBackground: '#F0F0F7',
  tabBar: '#FFFFFF',
  bubbleMine: '#6C5CE7',
  bubbleTheirs: '#F0F0F7',
  bubbleTextMine: '#FFFFFF',
  bubbleTextTheirs: '#1A1A2E',
  statusBarStyle: 'dark',
};

export const darkTheme = {
  mode: 'dark',
  background: '#121218',
  surface: '#1C1C26',
  card: '#1C1C26',
  text: '#F2F2F7',
  textSecondary: '#9A9AB0',
  border: '#2A2A36',
  primary: '#8A7CF0',
  primaryText: '#FFFFFF',
  accent: '#FF8A9B',
  success: '#2ECC71',
  danger: '#FF6B6B',
  inputBackground: '#242430',
  tabBar: '#1C1C26',
  bubbleMine: '#8A7CF0',
  bubbleTheirs: '#242430',
  bubbleTextMine: '#FFFFFF',
  bubbleTextTheirs: '#F2F2F7',
  statusBarStyle: 'light',
};
