export const THEME = {
  colors: {
    surface: '#FFFDF9',
    onSurface: '#1F1D2B',
    surfaceSecondary: '#F5F3ED',
    onSurfaceSecondary: '#2D2A38',
    surfaceTertiary: '#ECE6DE',
    onSurfaceTertiary: '#3E3A46',
    surfaceInverse: '#1F1D2B',
    onSurfaceInverse: '#FFFDF9',
    brand: '#FF6B6B',
    brandPrimary: '#FF6B6B',
    onBrandPrimary: '#FFFFFF',
    brandSecondary: '#FF8E53',
    onBrandSecondary: '#FFFFFF',
    brandTertiary: '#FFE3E3',
    onBrandTertiary: '#D93838',
    success: '#22C55E',
    onSuccess: '#FFFFFF',
    warning: '#F59E0B',
    onWarning: '#FFFFFF',
    error: '#EF4444',
    onError: '#FFFFFF',
    info: '#3B82F6',
    onInfo: '#FFFFFF',
    border: '#E5E0D8',
    borderStrong: '#D1C8BC',
    divider: '#EFECE6',
    tabInactive: '#9CA3AF',
    tabActive: '#FF6B6B',
    cardBackground: '#FFFFFF',
    overlayDark: 'rgba(15, 15, 20, 0.75)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    '2xl': 32,
    '3xl': 48,
  },
  radius: {
    sm: 8,
    md: 14,
    lg: 22,
    pill: 999,
  },
  typography: {
    scale: {
      xs: 11,
      sm: 13,
      base: 15,
      lg: 17,
      xl: 20,
      '2xl': 24,
      '3xl': 30,
    },
  },
};
